#if _WIN32
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_0,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_4,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_5,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_8,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_12,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_13,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_17,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_21,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_22,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_26,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_31,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_35,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_38,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_42,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_dos_47,
#else
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_0,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_4,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_5,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_8,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_12,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_13,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_17,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_21,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_22,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_26,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_31,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_35,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_38,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_42,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_dos_47,
#endif
