#ifdef _WIN32
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_0,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_1,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_2,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_3,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_4,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_5,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_6,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_10,
  (intptr_t)&((struct stringpool2_t *)0)->stringpool_aix_14,
#else
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_0,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_1,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_2,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_3,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_4,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_5,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_6,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_10,
  (int)(long)&((struct stringpool2_t *)0)->stringpool_aix_14,
#endif
